version: "3"
services:  

  # SECTION: POSTGRES
  # postgres-alpine
  pgdb:
    image: postgres:alpine
    container_name: postgresql
    restart: always
    # network_mode: host
    volumes:
      - ./data/pgsql/data:/var/lib/postgresql/data
      - ./data/pgsql/tables:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    # expose:
    #   - "5432"
    environment:
      POSTGRES_DB: DevDB
      POSTGRES_USER: PGAdmin
      POSTGRES_PASSWORD: SuperSecure1!

  # SECTION: POSTGRES ADMIN WEB GUI 
  pgweb:
    image: dpage/pgadmin4
    container_name: pgweb
    restart: always
    # network_mode: host
    depends_on:
      - pgdb
    volumes:
      - ./data/pgsql/pgadmin:/var/lib/pgadmin
    ports:
      - 80:80
    # expose:
    #   - "80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@example.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecure1!
      PGADMIN_LISTEN_PORT: 80

  # # SECTION: MYSQL
  # mysqldb:
  #   image: mysql:latest
  #   container_name: mysql
  #   restart: always
  #   # network_mode: host
  #   volumes:
  #     - ./data/mysql/data:/var/lib/mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - 3306:3306
  #   environment:
  #     MYSQL_ROOT_PASSWORD: SuperSecure1!
  #     MYSQL_USER: MYSQLAdmin
  #     MYSQL_PASSWORD: SuperSecure2!
  #     MYSQL_DATABASE: DevDB

  # # SECTION: MICROSOFT SQL SERVER
  # mssqldb:
  #   image: mcr.microsoft.com/mssql/server:2017-latest
  #   container_name: mssqlserver
  #   restart: always
  #     # network_mode: host
  #   volumes:
  #     - ./data/mssql/data:/var/opt/mssql
  #   ports:
  #     - 1433:1433
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: SuperSecure1!
  #     MSSQL_PID: Developer

  # # SECTION: MICROSOFT SQL SERVER MLSERVICES
  # mssqlml-db:
  #   image: mssql-server-mlservices
  #   build:
  #     context: ./dockerfiles/mssql-mlservices
  #     dockerfile: Dockerfile.mssqlml
  #   container_name: mssql-ml-server
  #   restart: always
  #   # network_mode: host
  #   volumes:
  #     - ./data/mssql/data:/var/opt/mssql
  #   ports:
  #     - 1433:1433
  #   environment:
  #     ACCEPT_EULA: Y
  #     ACCEPT_EULA_ML: Y
  #     SA_PASSWORD: SuperSecure1!
  #     MSSQL_PID: Developer

  # # SECTION: OTHER
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  # memcached:
  #   image: memcached:alpine
  #   container_name: memcached
  #   restart: always