version: "3"
services:  

  # postgres-alpine
  pgdb:
    image: postgres:alpine
    container_name: postgresql
    restart: always
    # network_mode: host
    volumes:
      - ./data/pgsql/data:/var/lib/postgresql/data
      - ./data/pgsql/tables:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    # expose:
    #   - "5432"
    environment:
      POSTGRES_DB: DevDB
      POSTGRES_USER: PGAdminUser
      POSTGRES_PASSWORD: SuperSecure1!


  # postgres-admin gui web interface:
  pgweb:
    image: dpage/pgadmin4
    container_name: pgweb
    restart: always
    # network_mode: host
    depends_on:
      - pgdb
    volumes:
      - ./data/pgsql/pgadmin:/var/lib/pgadmin
    ports:
      - 80:80
    # expose:
    #   - "80"
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@example.com
      PGADMIN_DEFAULT_PASSWORD: SuperSecure1!
      PGADMIN_LISTEN_PORT: 80

  # # mysql
  # mysql-db:
  #   image: mysql:latest
  #   container_name: mysql_db
  #   restart: always
  #   volumes:
  #     - mysql-data:/var/lib/mysql
  #   command: --default-authentication-plugin=mysql_native_password
  #   ports:
  #     - "3306:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Supersecureroot1!
  #     MYSQL_USER: MYSQLAdminUserName
  #     MYSQL_PASSWORD: Supersecureuser2!
  #     MYSQL_DATABASE: DevDB

  # # mssql
  # mssql-db:
  #   image: mcr.microsoft.com/mssql/server
  #   container_name: mssql-server
  #   restart: always
  #   volumes:
  #     - mssql-data:/var/opt/mssql
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     ACCEPT_EULA: Y
  #     SA_PASSWORD: Supersecureroot1!
  #     MSSQL_PID: Developer

  # # mssql w/ Python and R
  # mssqlml-db:
  #   image: mssql-ml-server
  #   build:
  #     context: ./mssql-mlservices
  #     dockerfile: Dockerfile
  #   container_name: mssql-ml-server
  #   restart: always
  #   volumes:
  #     - mssqlml-data:/var/opt/mssql
  #   environment:
  #     ACCEPT_EULA: Y
  #     ACCEPT_EULA_ML: Y
  #     SA_PASSWORD: Supersecureroot1!
  #     MSSQL_PID: Developer

  # # redis
  # redis:
  #   image: redis:alpine
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"

  # # memcached; TODO
  # memcached:
  #   image: memcached:alpine
  #   container_name: memcached
  #   restart: always


# volumes:
#   pg-data:
#   mysql-data:
#   mssql-data:
#   mssqlml-data:
